version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=tododb
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tododb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

